FROM python:3.10

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

RUN apt update && apt install \
    npm \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/
RUN npm install @openapitools/openapi-generator-cli -g
RUN openapi-python-client generate --url https://api.printerboks.dk/api/v1/openapi.json && \
    pip install --no-cache-dir fast-api-client


CMD ["python", "main:app"]
